name: Test on main

on:
  push:
    branches:
      - main
    tags: ["*"]

jobs:
  test:
    uses: ./.github/workflows/ReusableTest.yml
    with:
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
      arch: ${{ matrix.arch }}
      allow_failure: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.6"
          - "1"
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x64
        allow_failure: [false]
